apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: saas
spec:
  generators:
  - list:
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements:
        - cluster: gke-west-cluster
          url: https://34.94.110.55
          values:
            cloudProvider: 'gke'
            region: 'west'
        - cluster: gke-east-cluster
          url: https://kubernetes.default.svc
          values:
            cloudProvider: 'gke'
            region: 'east'
  template:
    metadata:
      name: '{{cluster}}-saas' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: https://github.com/liorhasson/argocd-example-apps.git
        targetRevision: HEAD
        path: 'multi-cluster/{{values.cloudProvider}}/{{values.region}}'
      destination:
        server: '{{url}}' # 'server' field of the secret
        namespace: saas
      syncPolicy:
        automated:
          selfHeal: true
