apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-rollout
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-rollout-canary
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values-production.yaml
  syncPolicy:
    automated:
      selfHeal: true
